import type { Metadata } from "next";
import { vt323, tiny5 } from "./ui/fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${tiny5.className} antialiased`}>{children}</body>
    </html>
  );
}
