import type { Metadata } from "next";
import "./globals.css";
import ThemeProvider from "./provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
        <body>{children}</body>
      </ThemeProvider>
    </html>
  );
}
